FROM python:3.7

EXPOSE 8501

COPY requirements.txt .
COPY forecast_streamlit_app.py .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ENTRYPOINT [ "streamlit", "run"]
CMD ["forecast_streamlit_app.py"]